### ISSUE TITLE
是否可以支持自定义Elasticsearch的索引名字

### ISSUE THREAD

**Issue by navyaijm2017** [Yourdream/rsbeat#2]
你好，比如有多个redis集群，我们希望每个redis集群的慢日志收集到各种的索引里面，目前配置文件中不支持自定义索引，可以支持嘛

**Comment by rockybean** [comment]
这个你可以通过跑多个rsbeat实例来实现，不同的实例用不同的配置，在不同的配置里面采用不同的索引名称
